version: '3.8'

services:
  api-gateway:
    build: .
    ports:
      - "8080:8080"
      - "9876:9876"
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - CONSUL_HOST=consul
      - CORS_ORIGIN=*
    depends_on:
      - redis
      - consul
    networks:
      - smartlearn-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - smartlearn-network

  consul:
    image: consul:latest
    ports:
      - "8500:8500"
    command: "agent -dev -client=0.0.0.0"
    networks:
      - smartlearn-network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - smartlearn-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - smartlearn-network

volumes:
  redis-data:
  grafana-data:

networks:
  smartlearn-network:
    driver: bridge 